"""Typed, immutable project configuration."""

from controller_learning.config.loader import (
    load_benchmark_config,
    load_level_config,
    load_project_config,
    load_track_config,
    load_vehicle_config,
)
from controller_learning.config.models import (
    ActuatorConfig,
    BenchmarkConfig,
    ConfigError,
    ControllerTimingConfig,
    EpisodeTimingConfig,
    LevelConfig,
    ProjectConfig,
    RankingConfig,
    SimulationConfig,
    TrackConfig,
    TrackGeneratorConfig,
    TrackRaceConfig,
    TrackRepresentationConfig,
    TrackValidationConfig,
    VehicleConfig,
    VehicleGeometryConfig,
)

__all__ = [
    "ActuatorConfig",
    "BenchmarkConfig",
    "ConfigError",
    "ControllerTimingConfig",
    "EpisodeTimingConfig",
    "LevelConfig",
    "ProjectConfig",
    "RankingConfig",
    "SimulationConfig",
    "TrackConfig",
    "TrackGeneratorConfig",
    "TrackRaceConfig",
    "TrackRepresentationConfig",
    "TrackValidationConfig",
    "VehicleConfig",
    "VehicleGeometryConfig",
    "load_benchmark_config",
    "load_level_config",
    "load_project_config",
    "load_track_config",
    "load_vehicle_config",
]
